version: '3'
services:
  nginx:
    image: nginx:1.18-alpine
    volumes:
      - ./njs:/etc/nginx/njs:ro
      - ./nginx/mirror_to_elastic.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    networks:
      elastic:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      discovery.type: single-node
    volumes:
      - ./temp_data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      elastic:
        aliases:
          - elasticsearch

networks:
  elastic:
